/** Every company, position and job track the game defines, transcribed from
 * `bitburner-src v3.0.1` company metadata (via the vendored copy
 * `sim/vendor/bitburner/src/Company/CompanyTable.ts`).
 *
 * The live scripts need this to plan work the player is NOT yet doing: which
 * fields a company offers, the promotion ladder behind each field, the
 * stat/reputation requirements per rung, and the salary/reputation
 * coefficients that price a rung before any rate has been measured. None of
 * that is observable through telemetry for a job we do not hold.
 *
 * Lives here rather than being read from the vendored copy because `shared/`
 * and `ui/` may not import `sim/` (tests/boundaries.test.ts). Pinned
 * entry-by-entry by `sim/tests/company-parity.test.ts` — after
 * `bun run vendor` bumps the tag, a failure there is the EXPECTED signal to
 * regenerate this transcription (scripted; zero-valued skill entries are
 * omitted).
 *
 * Pinned upstream definitions:
 * src/Company/data/JobTracks.ts, src/Company/data/CompanyPositionsMetadata.ts,
 * src/Company/data/CompaniesMetadata.ts */

export interface CompanyPositionInfo {
  readonly field: string;
  readonly next: string | null;
  readonly partTime?: boolean;
  /** Base salary per work cycle, before the company salary multiplier. */
  readonly salary: number;
  readonly repMult: number;
  /** Base per-skill requirements (zero entries omitted). The company's
   * statReqOffset is added to every nonzero entry. */
  readonly reqSkills?: Readonly<Record<string, number>>;
  /** Company reputation required (base; halved by a backdoor upstream). */
  readonly reqRep: number;
  /** Skill weights in the reputation performance sum (zero entries omitted). */
  readonly effectiveness: Readonly<Record<string, number>>;
  /** Experience per cycle before multipliers (zero entries omitted). */
  readonly expGain?: Readonly<Record<string, number>>;
}

export interface CompanyInfo {
  readonly positions: readonly string[];
  readonly expMult: number;
  readonly salaryMult: number;
  /** Added to every nonzero base skill requirement. */
  readonly statReqOffset: number;
  readonly faction?: string;
}

/** Field name -> ordered promotion ladder (entry rung first). */
export const JOB_TRACKS: Readonly<Record<string, readonly string[]>> = {
  "Software": ["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer"],
  "Software Consultant": ["Software Consultant","Senior Software Consultant"],
  "IT": ["IT Intern","IT Analyst","IT Manager","Systems Administrator"],
  "Security Engineer": ["Security Engineer"],
  "Network Engineer": ["Network Engineer","Network Administrator"],
  "Business": ["Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer"],
  "Business Consultant": ["Business Consultant","Senior Business Consultant"],
  "Security": ["Security Guard","Security Officer","Security Supervisor","Head of Security"],
  "Agent": ["Field Agent","Secret Agent","Special Operative"],
  "Employee": ["Employee"],
  "Part-time Employee": ["Part-time Employee"],
  "Waiter": ["Waiter"],
  "Part-time Waiter": ["Part-time Waiter"],
};

export const COMPANY_POSITIONS: Readonly<Record<string, CompanyPositionInfo>> = {
  "Software Engineering Intern": {"field":"Software","next":"Junior Software Engineer","salary":33,"repMult":0.9,"reqSkills":{"hacking":1},"reqRep":0,"effectiveness":{"hacking":85,"charisma":15},"expGain":{"hacking":0.05,"charisma":0.02}},
  "Junior Software Engineer": {"field":"Software","next":"Senior Software Engineer","salary":80,"repMult":1.1,"reqSkills":{"hacking":51},"reqRep":8000,"effectiveness":{"hacking":85,"charisma":15},"expGain":{"hacking":0.1,"charisma":0.05}},
  "Senior Software Engineer": {"field":"Software","next":"Lead Software Developer","salary":165,"repMult":1.3,"reqSkills":{"hacking":251,"charisma":51},"reqRep":40000,"effectiveness":{"hacking":80,"charisma":20},"expGain":{"hacking":0.4,"charisma":0.08}},
  "Lead Software Developer": {"field":"Software","next":"Head of Software","salary":500,"repMult":1.5,"reqSkills":{"hacking":401,"charisma":151},"reqRep":200000,"effectiveness":{"hacking":75,"charisma":25},"expGain":{"hacking":0.8,"charisma":0.1}},
  "Head of Software": {"field":"Software","next":"Head of Engineering","salary":800,"repMult":1.6,"reqSkills":{"hacking":501,"charisma":251},"reqRep":400000,"effectiveness":{"hacking":75,"charisma":25},"expGain":{"hacking":1,"charisma":0.5}},
  "Head of Engineering": {"field":"Software","next":"Vice President of Technology","salary":1650,"repMult":1.6,"reqSkills":{"hacking":501,"charisma":251},"reqRep":800000,"effectiveness":{"hacking":75,"charisma":25},"expGain":{"hacking":1.1,"charisma":0.5}},
  "Vice President of Technology": {"field":"Software","next":"Chief Technology Officer","salary":2310,"repMult":1.75,"reqSkills":{"hacking":601,"charisma":401},"reqRep":1600000,"effectiveness":{"hacking":70,"charisma":30},"expGain":{"hacking":1.2,"charisma":0.6}},
  "Chief Technology Officer": {"field":"Software","next":null,"salary":2640,"repMult":2,"reqSkills":{"hacking":751,"charisma":501},"reqRep":3200000,"effectiveness":{"hacking":65,"charisma":35},"expGain":{"hacking":1.5,"charisma":1}},
  "IT Intern": {"field":"IT","next":"IT Analyst","salary":26,"repMult":0.9,"reqSkills":{"hacking":1},"reqRep":0,"effectiveness":{"hacking":90,"charisma":10},"expGain":{"hacking":0.04,"charisma":0.01}},
  "IT Analyst": {"field":"IT","next":"IT Manager","salary":66,"repMult":1.1,"reqSkills":{"hacking":26},"reqRep":7000,"effectiveness":{"hacking":85,"charisma":15},"expGain":{"hacking":0.08,"charisma":0.02}},
  "IT Manager": {"field":"IT","next":"Systems Administrator","salary":132,"repMult":1.3,"reqSkills":{"hacking":151,"charisma":51},"reqRep":35000,"effectiveness":{"hacking":80,"charisma":20},"expGain":{"hacking":0.3,"charisma":0.1}},
  "Systems Administrator": {"field":"IT","next":"Head of Engineering","salary":410,"repMult":1.4,"reqSkills":{"hacking":251,"charisma":76},"reqRep":175000,"effectiveness":{"hacking":80,"charisma":20},"expGain":{"hacking":0.5,"charisma":0.2}},
  "Security Engineer": {"field":"Security Engineer","next":"Head of Engineering","salary":121,"repMult":1.2,"reqSkills":{"hacking":151,"charisma":26},"reqRep":35000,"effectiveness":{"hacking":85,"charisma":15},"expGain":{"hacking":0.4,"charisma":0.05}},
  "Network Engineer": {"field":"Network Engineer","next":"Network Administrator","salary":121,"repMult":1.2,"reqSkills":{"hacking":151,"charisma":26},"reqRep":35000,"effectiveness":{"hacking":85,"charisma":15},"expGain":{"hacking":0.4,"charisma":0.05}},
  "Network Administrator": {"field":"Network Engineer","next":"Head of Engineering","salary":410,"repMult":1.3,"reqSkills":{"hacking":251,"charisma":76},"reqRep":175000,"effectiveness":{"hacking":80,"charisma":20},"expGain":{"hacking":0.5,"charisma":0.1}},
  "Business Intern": {"field":"Business","next":"Business Analyst","salary":46,"repMult":0.9,"reqSkills":{"hacking":1,"charisma":1},"reqRep":0,"effectiveness":{"hacking":10,"charisma":90},"expGain":{"hacking":0.01,"charisma":0.08}},
  "Business Analyst": {"field":"Business","next":"Business Manager","salary":100,"repMult":1.1,"reqSkills":{"hacking":6,"charisma":51},"reqRep":8000,"effectiveness":{"hacking":15,"charisma":85},"expGain":{"hacking":0.02,"charisma":0.15}},
  "Business Manager": {"field":"Business","next":"Operations Manager","salary":200,"repMult":1.3,"reqSkills":{"hacking":51,"charisma":101},"reqRep":40000,"effectiveness":{"hacking":15,"charisma":85},"expGain":{"hacking":0.02,"charisma":0.3}},
  "Operations Manager": {"field":"Business","next":"Chief Financial Officer","salary":660,"repMult":1.5,"reqSkills":{"hacking":51,"charisma":226},"reqRep":200000,"effectiveness":{"hacking":15,"charisma":85},"expGain":{"hacking":0.02,"charisma":0.4}},
  "Chief Financial Officer": {"field":"Business","next":"Chief Executive Officer","salary":1950,"repMult":1.6,"reqSkills":{"hacking":76,"charisma":501},"reqRep":800000,"effectiveness":{"hacking":10,"charisma":90},"expGain":{"hacking":0.05,"charisma":1}},
  "Chief Executive Officer": {"field":"Business","next":null,"salary":3900,"repMult":1.75,"reqSkills":{"hacking":101,"charisma":751},"reqRep":3200000,"effectiveness":{"hacking":10,"charisma":90},"expGain":{"hacking":0.05,"charisma":1.5}},
  "Security Guard": {"field":"Security","next":"Security Officer","salary":50,"repMult":1,"reqSkills":{"strength":51,"defense":51,"dexterity":51,"agility":51,"charisma":1},"reqRep":0,"effectiveness":{"hacking":5,"strength":20,"defense":20,"dexterity":20,"agility":20,"charisma":15},"expGain":{"hacking":0.01,"strength":0.04,"defense":0.04,"dexterity":0.04,"agility":0.04,"charisma":0.02}},
  "Security Officer": {"field":"Security","next":"Security Supervisor","salary":195,"repMult":1.1,"reqSkills":{"hacking":26,"strength":151,"defense":151,"dexterity":151,"agility":151,"charisma":51},"reqRep":8000,"effectiveness":{"hacking":10,"strength":20,"defense":20,"dexterity":20,"agility":20,"charisma":10},"expGain":{"hacking":0.02,"strength":0.1,"defense":0.1,"dexterity":0.1,"agility":0.1,"charisma":0.05}},
  "Security Supervisor": {"field":"Security","next":"Head of Security","salary":660,"repMult":1.25,"reqSkills":{"hacking":26,"strength":251,"defense":251,"dexterity":251,"agility":251,"charisma":101},"reqRep":36000,"effectiveness":{"hacking":10,"strength":15,"defense":15,"dexterity":15,"agility":15,"charisma":30},"expGain":{"hacking":0.02,"strength":0.12,"defense":0.12,"dexterity":0.12,"agility":0.12,"charisma":0.1}},
  "Head of Security": {"field":"Security","next":null,"salary":1320,"repMult":1.4,"reqSkills":{"hacking":51,"strength":501,"defense":501,"dexterity":501,"agility":501,"charisma":151},"reqRep":144000,"effectiveness":{"hacking":10,"strength":15,"defense":15,"dexterity":15,"agility":15,"charisma":30},"expGain":{"hacking":0.05,"strength":0.15,"defense":0.15,"dexterity":0.15,"agility":0.15,"charisma":0.15}},
  "Field Agent": {"field":"Agent","next":"Secret Agent","salary":330,"repMult":1,"reqSkills":{"hacking":101,"strength":101,"defense":101,"dexterity":101,"agility":101,"charisma":101},"reqRep":8000,"effectiveness":{"hacking":10,"strength":15,"defense":15,"dexterity":20,"agility":20,"charisma":20},"expGain":{"hacking":0.04,"strength":0.08,"defense":0.08,"dexterity":0.08,"agility":0.08,"charisma":0.05}},
  "Secret Agent": {"field":"Agent","next":"Special Operative","salary":990,"repMult":1.25,"reqSkills":{"hacking":201,"strength":251,"defense":251,"dexterity":251,"agility":251,"charisma":201},"reqRep":32000,"effectiveness":{"hacking":15,"strength":15,"defense":15,"dexterity":20,"agility":20,"charisma":15},"expGain":{"hacking":0.1,"strength":0.15,"defense":0.15,"dexterity":0.15,"agility":0.15,"charisma":0.1}},
  "Special Operative": {"field":"Agent","next":null,"salary":2000,"repMult":1.5,"reqSkills":{"hacking":251,"strength":501,"defense":501,"dexterity":501,"agility":501,"charisma":251},"reqRep":162000,"effectiveness":{"hacking":15,"strength":15,"defense":15,"dexterity":20,"agility":20,"charisma":15},"expGain":{"hacking":0.15,"strength":0.2,"defense":0.2,"dexterity":0.2,"agility":0.2,"charisma":0.15}},
  "Waiter": {"field":"Waiter","next":null,"salary":22,"repMult":1,"reqRep":0,"effectiveness":{"strength":10,"dexterity":10,"agility":10,"charisma":70},"expGain":{"strength":0.02,"defense":0.02,"dexterity":0.02,"agility":0.02,"charisma":0.05}},
  "Employee": {"field":"Employee","next":null,"salary":22,"repMult":1,"reqRep":0,"effectiveness":{"strength":10,"dexterity":10,"agility":10,"charisma":70},"expGain":{"strength":0.02,"defense":0.02,"dexterity":0.02,"agility":0.02,"charisma":0.04}},
  "Software Consultant": {"field":"Software Consultant","next":"Senior Software Consultant","salary":66,"repMult":1,"reqSkills":{"hacking":51},"reqRep":0,"effectiveness":{"hacking":80,"charisma":20},"expGain":{"hacking":0.08,"charisma":0.03}},
  "Senior Software Consultant": {"field":"Software Consultant","next":null,"salary":132,"repMult":1.2,"reqSkills":{"hacking":251,"charisma":51},"reqRep":0,"effectiveness":{"hacking":75,"charisma":25},"expGain":{"hacking":0.25,"charisma":0.06}},
  "Business Consultant": {"field":"Business Consultant","next":"Senior Business Consultant","salary":66,"repMult":1,"reqSkills":{"hacking":6,"charisma":51},"reqRep":0,"effectiveness":{"hacking":20,"charisma":80},"expGain":{"hacking":0.015,"charisma":0.15}},
  "Senior Business Consultant": {"field":"Business Consultant","next":null,"salary":525,"repMult":1.2,"reqSkills":{"hacking":51,"charisma":226},"reqRep":0,"effectiveness":{"hacking":15,"charisma":85},"expGain":{"hacking":0.015,"charisma":0.3}},
  "Part-time Waiter": {"field":"Waiter","next":null,"partTime":true,"salary":20,"repMult":1,"reqRep":0,"effectiveness":{"strength":10,"dexterity":10,"agility":10,"charisma":70},"expGain":{"strength":0.0075,"defense":0.0075,"dexterity":0.0075,"agility":0.0075,"charisma":0.04}},
  "Part-time Employee": {"field":"Employee","next":null,"partTime":true,"salary":20,"repMult":1,"reqRep":0,"effectiveness":{"strength":10,"dexterity":10,"agility":10,"charisma":70},"expGain":{"strength":0.0075,"defense":0.0075,"dexterity":0.0075,"agility":0.0075,"charisma":0.03}},
};

export const COMPANIES: Readonly<Record<string, CompanyInfo>> = {
  "ECorp": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":3,"salaryMult":3,"statReqOffset":249,"faction":"ECorp"},
  "MegaCorp": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":3,"salaryMult":3,"statReqOffset":249,"faction":"MegaCorp"},
  "Bachman & Associates": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":2.6,"salaryMult":2.6,"statReqOffset":224,"faction":"Bachman & Associates"},
  "Blade Industries": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":2.75,"salaryMult":2.75,"statReqOffset":224,"faction":"Blade Industries"},
  "NWO": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":2.75,"salaryMult":2.75,"statReqOffset":249,"faction":"NWO"},
  "Clarke Incorporated": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":2.25,"salaryMult":2.25,"statReqOffset":224,"faction":"Clarke Incorporated"},
  "OmniTek Incorporated": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":2.25,"salaryMult":2.25,"statReqOffset":224,"faction":"OmniTek Incorporated"},
  "Four Sigma": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":2.5,"salaryMult":2.5,"statReqOffset":224,"faction":"Four Sigma"},
  "KuaiGong International": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":2.2,"salaryMult":2.2,"statReqOffset":224,"faction":"KuaiGong International"},
  "Fulcrum Technologies": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer"],"expMult":2,"salaryMult":2,"statReqOffset":224,"faction":"Fulcrum Secret Technologies"},
  "Storm Technologies": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Software Consultant","Senior Software Consultant","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer"],"expMult":1.8,"salaryMult":1.8,"statReqOffset":199},
  "DefComm": {"positions":["Chief Executive Officer","Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Software Consultant","Senior Software Consultant","Business Consultant","Senior Business Consultant"],"expMult":1.75,"salaryMult":1.75,"statReqOffset":199},
  "Helios Labs": {"positions":["Chief Executive Officer","Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Software Consultant","Senior Software Consultant","Business Consultant","Senior Business Consultant"],"expMult":1.8,"salaryMult":1.8,"statReqOffset":199},
  "VitaLife": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Software Consultant","Senior Software Consultant"],"expMult":1.8,"salaryMult":1.8,"statReqOffset":199},
  "Icarus Microsystems": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Software Consultant","Senior Software Consultant"],"expMult":1.9,"salaryMult":1.9,"statReqOffset":199},
  "Universal Energy": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Software Consultant","Senior Software Consultant"],"expMult":2,"salaryMult":2,"statReqOffset":199},
  "Galactic Cybersystems": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Software Consultant","Senior Software Consultant"],"expMult":1.9,"salaryMult":1.9,"statReqOffset":199},
  "AeroCorp": {"positions":["Operations Manager","Chief Executive Officer","Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Security Guard","Security Officer","Security Supervisor","Head of Security","Business Consultant","Senior Business Consultant"],"expMult":1.7,"salaryMult":1.7,"statReqOffset":199},
  "Omnia Cybersystems": {"positions":["Operations Manager","Chief Executive Officer","Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Security Guard","Security Officer","Security Supervisor","Head of Security","Business Consultant","Senior Business Consultant"],"expMult":1.7,"salaryMult":1.7,"statReqOffset":199},
  "Solaris Space Systems": {"positions":["Operations Manager","Chief Executive Officer","Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Security Guard","Security Officer","Security Supervisor","Head of Security","Business Consultant","Senior Business Consultant"],"expMult":1.7,"salaryMult":1.7,"statReqOffset":199},
  "DeltaOne": {"positions":["Operations Manager","Chief Executive Officer","Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Security Guard","Security Officer","Security Supervisor","Head of Security","Business Consultant","Senior Business Consultant"],"expMult":1.6,"salaryMult":1.6,"statReqOffset":199},
  "Global Pharmaceuticals": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Software Consultant","Senior Software Consultant","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":1.8,"salaryMult":1.8,"statReqOffset":224},
  "Nova Medical": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Software Consultant","Senior Software Consultant","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":1.75,"salaryMult":1.75,"statReqOffset":199},
  "Central Intelligence Agency": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Network Engineer","Network Administrator","Security Engineer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Security Guard","Security Officer","Security Supervisor","Head of Security","Field Agent","Secret Agent","Special Operative"],"expMult":2,"salaryMult":2,"statReqOffset":149},
  "National Security Agency": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Network Engineer","Network Administrator","Security Engineer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Security Guard","Security Officer","Security Supervisor","Head of Security","Field Agent","Secret Agent","Special Operative"],"expMult":2,"salaryMult":2,"statReqOffset":149},
  "Watchdog Security": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Network Engineer","Network Administrator","IT Intern","IT Analyst","IT Manager","Systems Administrator","Security Guard","Security Officer","Security Supervisor","Head of Security","Field Agent","Secret Agent","Special Operative","Software Consultant","Senior Software Consultant"],"expMult":1.5,"salaryMult":1.5,"statReqOffset":124},
  "LexoCorp": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Software Consultant","Senior Software Consultant","Business Intern","Business Analyst","Business Manager","Operations Manager","Chief Financial Officer","Chief Executive Officer","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":1.4,"salaryMult":1.4,"statReqOffset":99},
  "Rho Construction": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Business Intern","Business Analyst","Business Manager","Operations Manager"],"expMult":1.3,"salaryMult":1.3,"statReqOffset":49},
  "Alpha Enterprises": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Business Intern","Business Analyst","Business Manager","Operations Manager","Software Consultant","Senior Software Consultant"],"expMult":1.5,"salaryMult":1.5,"statReqOffset":99},
  "Aevum Police Headquarters": {"positions":["Security Guard","Security Officer","Security Supervisor","Head of Security","Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer"],"expMult":1.3,"salaryMult":1.3,"statReqOffset":99},
  "SysCore Securities": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer"],"expMult":1.3,"salaryMult":1.3,"statReqOffset":124},
  "CompuTek": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer"],"expMult":1.2,"salaryMult":1.2,"statReqOffset":74},
  "NetLink Technologies": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer"],"expMult":1.2,"salaryMult":1.2,"statReqOffset":99},
  "Carmichael Security": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","IT Intern","IT Analyst","IT Manager","Systems Administrator","Network Engineer","Network Administrator","Security Engineer","Software Consultant","Senior Software Consultant","Field Agent","Secret Agent","Special Operative","Security Guard","Security Officer","Security Supervisor","Head of Security"],"expMult":1.2,"salaryMult":1.2,"statReqOffset":74},
  "FoodNStuff": {"positions":["Employee","Part-time Employee"],"expMult":1,"salaryMult":1,"statReqOffset":0},
  "Joe's Guns": {"positions":["Employee","Part-time Employee"],"expMult":1,"salaryMult":1,"statReqOffset":0},
  "Omega Software": {"positions":["Software Engineering Intern","Junior Software Engineer","Senior Software Engineer","Lead Software Developer","Head of Software","Head of Engineering","Vice President of Technology","Chief Technology Officer","Software Consultant","Senior Software Consultant","IT Intern","IT Analyst","IT Manager","Systems Administrator"],"expMult":1.1,"salaryMult":1.1,"statReqOffset":49},
  "Noodle Bar": {"positions":["Waiter","Part-time Waiter"],"expMult":1,"salaryMult":1,"statReqOffset":0},
};
