import { describe, expect, test } from "bun:test";
import {
  DIRECTIONS,
  ahead,
  emptyMaze,
  expectedExit,
  key,
  readCoords,
  readExit,
  readSurroundings,
  stepMaze,
  type Cell,
  type MazeKnowledge,
} from "../shared/strategy/dnet/maze.ts";

/** The walker, against mazes it has never seen.
 *
 * The engine half is reproduced here from `labyrinth.ts` rather than stubbed,
 * because the two things most likely to be wrong are both in the wire format:
 * that a step is TWO cells while the wall is the one between, and that the 3x3
 * render is indexed rows-then-columns with y growing downward. A hand-written
 * stub would encode whatever misreading the solver already has.
 *
 * The mazes are generated by recursive backtracking, the standard
 * odd-coordinates-are-cells layout upstream also uses. What matters for the
 * walker is only that the layout matches, not that the generator does. */

const WALL = "#";
const PATH = " ";

/** A perfect maze: every cell reachable, exactly one route between any two. */
function generateMaze(cellsWide: number, cellsHigh: number, rng: () => number): string[] {
  const width = cellsWide * 2 + 1;
  const height = cellsHigh * 2 + 1;
  const grid = Array.from({ length: height }, () => new Array<string>(width).fill(WALL));

  const carve = (cx: number, cy: number): void => {
    grid[cy * 2 + 1]![cx * 2 + 1] = PATH;
    const order = [0, 1, 2, 3].sort(() => rng() - 0.5);
    for (const d of order) {
      const [dx, dy] = [[0, -1], [1, 0], [0, 1], [-1, 0]][d]!;
      const nx = cx + dx;
      const ny = cy + dy;
      if (nx < 0 || ny < 0 || nx >= cellsWide || ny >= cellsHigh) continue;
      if (grid[ny * 2 + 1]![nx * 2 + 1] === PATH) continue;
      grid[cy * 2 + 1 + dy]![cx * 2 + 1 + dx] = PATH;
      carve(nx, ny);
    }
  };
  carve(0, 0);
  return grid.map((row) => row.join(""));
}

/** `getSurroundingsVisualized(maze, x, y, 1, showPlayer, showEnd)`. */
function render(maze: string[], at: Cell, exit: Cell, showEnd = false): string {
  const rows: string[] = [];
  for (let i = at[1] - 1; i <= at[1] + 1; i++) {
    let row = "";
    for (let j = at[0] - 1; j <= at[0] + 1; j++) {
      if (i === at[1] && j === at[0]) {
        row += "@";
        continue;
      }
      if (showEnd && i === exit[1] && j === exit[0]) {
        row += "X";
        continue;
      }
      row += maze[i]?.[j] ?? PATH;
    }
    rows.push(row);
  }
  return rows.join("\n");
}

interface Walk {
  solved: boolean;
  steps: number;
  reason?: string;
}

/** Drive the walker exactly as `handleLabyrinthPassword` would. */
function walk(maze: string[], start: Cell, exit: Cell, cap = 20_000): Walk {
  const bounds = { width: maze[0]!.length, height: maze.length };
  let known: MazeKnowledge = emptyMaze();
  let at: Cell = start;
  let steps = 0;

  while (steps < cap) {
    const step = stepMaze(known, at, render(maze, at, exit), bounds);
    if (step.kind !== "go") return { solved: false, steps, reason: step.reason };
    known = step.known;
    steps++;

    // The engine's move handler: the wall is at +1, the landing at +2.
    const [dx, dy] = [
      ahead(at, step.direction)[0] - at[0],
      ahead(at, step.direction)[1] - at[1],
    ];
    const wall: Cell = [at[0] + dx / 2, at[1] + dy / 2];
    if (maze[wall[1]]?.[wall[0]] !== PATH) {
      // "You cannot go that way." Position is unchanged — and the walker must
      // not believe otherwise, or it will desync from the engine permanently.
      continue;
    }
    at = ahead(at, step.direction);
    if (at[0] === exit[0] && at[1] === exit[1]) return { solved: true, steps };
  }
  return { solved: false, steps, reason: "ran past the cap" };
}

const seeded = (seed: number): (() => number) => {
  let state = seed >>> 0;
  return () => {
    state = (state * 1664525 + 1013904223) >>> 0;
    return state / 0x1_0000_0000;
  };
};

describe("the wire format is read the way the engine writes it", () => {
  test("a 3x3 render maps to the four walls", () => {
    // Rows are y-1..y+1, columns x-1..x+1. Open north and east only.
    const walls = readSurroundings("# #\n#@ \n###");
    expect(walls).toEqual({ north: true, east: true, south: false, west: false });
  });

  test("the exit overlay counts as passable, because it sits on a path square", () => {
    const walls = readSurroundings("#X#\n#@ \n###");
    expect(walls?.north).toBe(true);
  });

  test("a render that is not 3x3 stops the walker rather than guessing", () => {
    expect(readSurroundings("##")).toBeUndefined();
    expect(readSurroundings("")).toBeUndefined();
  });

  test("both phrasings of the position message are read", () => {
    // A successful step and a refused one report differently, and the walker
    // needs the position from either.
    expect(readCoords("You have moved to 12,34.")).toEqual([12, 34]);
    expect(readCoords("You cannot go that way. You are still at 7,9.")).toEqual([7, 9]);
    expect(readCoords("You have discovered the end of the labyrinth.")).toBeUndefined();
  });

  test("the exit is located from a wider render when one shows it", () => {
    // labradar renders radius 3 WITH the overlay; the move handler does not.
    const wide = ["#######", "#######", "#######", "###@###", "#####X#", "#######", "#######"].join("\n");
    expect(readExit(wide, [10, 10])).toEqual([12, 11]);
  });

});

describe("the walker solves mazes it cannot see", () => {
  test("100 mazes at the first lab's size are all solved", () => {
    // NormalLab is 20x14 cells.
    const rng = seeded(0x5a2e);
    let worst = 0;
    for (let i = 0; i < 100; i++) {
      const maze = generateMaze(20, 14, rng);
      const exit: Cell = [maze[0]!.length - 2, maze.length - 2];
      const result = walk(maze, [1, 1], exit);
      expect(result.solved, `maze ${i}: ${result.reason}`).toBe(true);
      worst = Math.max(worst, result.steps);
    }
    // A perfect maze of 280 cells; depth-first with a corner bias walks a good
    // deal less than the ~560 steps a full traversal-and-back would cost.
    expect(worst).toBeLessThan(560);
  });

  test("the largest lab size is solved too", () => {
    // UberLab and above are 60x40 cells — 2400 of them.
    const rng = seeded(0x6040);
    for (let i = 0; i < 10; i++) {
      const maze = generateMaze(60, 40, rng);
      const exit: Cell = [maze[0]!.length - 2, maze.length - 2];
      const result = walk(maze, [1, 1], exit);
      expect(result.solved, `maze ${i}: ${result.reason}`).toBe(true);
    }
  });

  test("a randomly offset start and exit are handled", () => {
    // getRandomOffset moves both by 0, 2 or 4 — so neither corner is where the
    // walker would naively assume.
    const rng = seeded(0x0ff5e7);
    for (const offset of [0, 2, 4]) {
      const maze = generateMaze(20, 14, rng);
      const exit: Cell = [maze[0]!.length - 2 - offset, maze.length - 2 - offset];
      const result = walk(maze, [1 + offset, 1 + offset], exit);
      expect(result.solved, `offset ${offset}: ${result.reason}`).toBe(true);
    }
  });

  test("a wall refusal does not desync the walker", () => {
    // The engine answers a blocked move with the position UNCHANGED. A walker
    // that assumed it had moved would be reasoning about the wrong cell from
    // then on, and would never recover.
    const maze = ["#####", "#   #", "#####"];
    const known = emptyMaze();
    const step = stepMaze(known, [1, 1], render(maze, [1, 1], [3, 1]), { width: 5, height: 3 });
    expect(step.kind).toBe("go");
    // North is a wall here, so it must not be chosen.
    if (step.kind === "go") expect(step.direction).not.toBe("north");
  });

  test("a sealed cell is reported as exhausted, not walked forever", () => {
    // Every route walked and no exit found means our model of the maze is
    // wrong — that has to be loud rather than an infinite loop.
    const maze = ["###", "#@#", "###"];
    const step = stepMaze(emptyMaze(), [1, 1], render(maze, [1, 1], [1, 1]), { width: 3, height: 3 });
    expect(step.kind).toBe("exhausted");
  });

  test("the walk is deterministic, so a resumed walker continues", () => {
    const rng = seeded(0xdead);
    const maze = generateMaze(10, 10, rng);
    const exit: Cell = [maze[0]!.length - 2, maze.length - 2];
    const a = walk(maze, [1, 1], exit);
    const b = walk(maze, [1, 1], exit);
    expect(a.steps).toBe(b.steps);
  });

  test("knowledge is plain JSON, so it survives the ledger round trip", () => {
    const maze = generateMaze(6, 6, seeded(7));
    const step = stepMaze(emptyMaze(), [1, 1], render(maze, [1, 1], [11, 11]), { width: 13, height: 13 });
    expect(step.kind).toBe("go");
    if (step.kind !== "go") return;
    const revived = JSON.parse(JSON.stringify(step.known)) as MazeKnowledge;
    expect(revived).toEqual(step.known);
    // And it keeps working after the round trip.
    const next = stepMaze(revived, ahead([1, 1], step.direction), render(maze, ahead([1, 1], step.direction), [11, 11]), { width: 13, height: 13 });
    expect(next.kind === "go" || next.kind === "exhausted").toBe(true);
  });

  test("the same cell is never queued twice, which is what bounds the walk", () => {
    const maze = generateMaze(8, 8, seeded(99));
    const exit: Cell = [maze[0]!.length - 2, maze.length - 2];
    let known = emptyMaze();
    let at: Cell = [1, 1];
    for (let i = 0; i < 400; i++) {
      const step = stepMaze(known, at, render(maze, at, exit), { width: 17, height: 17 });
      if (step.kind !== "go") break;
      known = step.known;
      expect(new Set(known.visited).size, "a cell was recorded twice").toBe(known.visited.length);
      const wall: Cell = [(at[0] + ahead(at, step.direction)[0]) / 2, (at[1] + ahead(at, step.direction)[1]) / 2];
      if (maze[wall[1]]?.[wall[0]] === PATH) at = ahead(at, step.direction);
      if (key(at) === key(exit)) break;
    }
    expect(key(at)).toBe(key(exit));
  });
});
