/** Netscript RAM costs, transcribed from
 * bitburner-src/src/Netscript/RamCostGenerator.ts @ v3.0.1.
 *
 * Transcribed rather than vendored: RamCostGenerator imports `@player` and
 * `NSFull`, and that import graph detonates into the whole game the same way
 * Hacking.ts's DarknetServer import does (see tools/vendor.ts). The tree below
 * is a pure literal, so copying it is safe — but it is NOT drift-detected.
 * Re-read the file when bumping the pinned tag.
 *
 * This matters more than it looks. probe-runner prices every probe with
 * ns.getFunctionRamCost and packs what fits the dodge budget; if these numbers
 * are wrong, the simulated packer makes different decisions from the real one
 * and the whole "is my probe schedule affordable" question becomes fiction. */

/** RamCostConstants, verbatim (only the entries this tree references). */
const C = {
  Base: 1.6,
  CorporationInfo: 10,
  CorporationAction: 20,
  Hack: 0.1,
  Grow: 0.15,
  Weaken: 0.15,
  Scan: 0.2,
  RecentScripts: 0.2,
  PortProgram: 0.05,
  Run: 1.0,
  Exec: 1.3,
  Spawn: 2.0,
  Scp: 0.6,
  Kill: 0.5,
  HasRootAccess: 0.05,
  GetHostname: 0.05,
  GetHackingLevel: 0.05,
  GetServer: 0.1,
  GetServerMaxRam: 0.05,
  GetServerUsedRam: 0.05,
  FileExists: 0.1,
  IsRunning: 0.1,
  Hacknet: 0.5,
  GetStock: 2.0,
  BuySellStock: 2.5,
  ArbScript: 1.0,
  GetScript: 0.1,
  GetRunningScript: 0.3,
  GetHackTime: 0.05,
  GetFavorToDonate: 0.1,
  CodingContractBase: 10,
  SleeveBase: 4,
  GetMoneySourcesCost: 1.0,
  SingularityFn1: 2,
  SingularityFn2: 3,
  SingularityFn3: 5,
  GangApiBase: 4,
  BladeburnerApiBase: 4,
  StanekWidth: 0.4,
  StanekHeight: 0.4,
  StanekFragmentDefinitions: 0,
  StanekPlacedFragments: 5,
  InfiltrationGetInfiltrations: 15,
  CycleTiming: 0,
} as const;

export const SCRIPT_BASE_RAM_GB = C.Base;

/** A Singularity cost: 16x without SF4, 4x at SF4.2, 1x at SF4.3 or inside
 * BN4. Modelled as data so the tree stays a literal. */
interface Sf4Cost {
  sf4: number;
}

type CostNode = number | Sf4Cost | { [key: string]: CostNode };

function sf4(cost: number): Sf4Cost {
  return { sf4: cost };
}

/** Context for the Singularity multiplier: SF4Cost() reads the live player. */
export interface RamCostContext {
  bitNode?: number;
  /** Active SF4 level (already merged with bitNodeOptions overrides). */
  sf4Level?: number;
}

const hacknet: CostNode = {
  numNodes: C.Hacknet,
  purchaseNode: C.Hacknet,
  getPurchaseNodeCost: C.Hacknet,
  getNodeStats: C.Hacknet,
  upgradeLevel: C.Hacknet,
  upgradeRam: C.Hacknet,
  upgradeCore: C.Hacknet,
  upgradeCache: C.Hacknet,
  getLevelUpgradeCost: C.Hacknet,
  getRamUpgradeCost: C.Hacknet,
  getCoreUpgradeCost: C.Hacknet,
  getCacheUpgradeCost: C.Hacknet,
  numHashes: C.Hacknet,
  hashCost: C.Hacknet,
  spendHashes: C.Hacknet,
  maxNumNodes: C.Hacknet,
  hashCapacity: C.Hacknet,
  getHashUpgrades: C.Hacknet,
  getHashUpgradeLevel: C.Hacknet,
  getStudyMult: C.Hacknet,
  getTrainingMult: C.Hacknet,
};

const stock: CostNode = {
  getConstants: 0,
  hasWseAccount: 0.05,
  hasTixApiAccess: 0.05,
  has4SData: 0.05,
  has4SDataTixApi: 0.05,
  getBonusTime: 0,
  nextUpdate: C.CycleTiming,
  getSymbols: C.GetStock,
  getPrice: C.GetStock,
  getOrganization: C.GetStock,
  getAskPrice: C.GetStock,
  getBidPrice: C.GetStock,
  getPosition: C.GetStock,
  getMaxShares: C.GetStock,
  getPurchaseCost: C.GetStock,
  getSaleGain: C.GetStock,
  buyStock: C.BuySellStock,
  sellStock: C.BuySellStock,
  buyShort: C.BuySellStock,
  sellShort: C.BuySellStock,
  placeOrder: C.BuySellStock,
  cancelOrder: C.BuySellStock,
  getOrders: C.BuySellStock,
  getVolatility: C.BuySellStock,
  getForecast: C.BuySellStock,
  purchase4SMarketData: C.BuySellStock,
  purchase4SMarketDataTixApi: C.BuySellStock,
  purchaseWseAccount: C.BuySellStock,
  purchaseTixApi: C.BuySellStock,
};

const singularity: CostNode = {
  universityCourse: sf4(C.SingularityFn1),
  gymWorkout: sf4(C.SingularityFn1),
  travelToCity: sf4(C.SingularityFn1),
  goToLocation: sf4(C.SingularityFn3),
  purchaseTor: sf4(C.SingularityFn1),
  purchaseProgram: sf4(C.SingularityFn1),
  getCurrentServer: sf4(C.SingularityFn1),
  getCompanyPositionInfo: sf4(C.SingularityFn1),
  getCompanyPositions: sf4(C.SingularityFn1),
  cat: sf4(C.SingularityFn1 / 4),
  connect: sf4(C.SingularityFn1),
  manualHack: sf4(C.SingularityFn1),
  installBackdoor: sf4(C.SingularityFn1),
  getDarkwebProgramCost: sf4(C.SingularityFn1 / 4),
  getDarkwebPrograms: sf4(C.SingularityFn1 / 4),
  hospitalize: sf4(C.SingularityFn1 / 4),
  isBusy: sf4(C.SingularityFn1 / 4),
  stopAction: sf4(C.SingularityFn1 / 2),
  upgradeHomeRam: sf4(C.SingularityFn2),
  upgradeHomeCores: sf4(C.SingularityFn2),
  getUpgradeHomeRamCost: sf4(C.SingularityFn2 / 2),
  getUpgradeHomeCoresCost: sf4(C.SingularityFn2 / 2),
  workForCompany: sf4(C.SingularityFn2),
  applyToCompany: sf4(C.SingularityFn2),
  quitJob: sf4(C.SingularityFn2),
  getCompanyRep: sf4(C.SingularityFn2 / 3),
  getCompanyFavor: sf4(C.SingularityFn2 / 3),
  getCompanyFavorGain: sf4(C.SingularityFn2 / 4),
  getFactionInviteRequirements: sf4(C.SingularityFn2),
  getFactionEnemies: sf4(C.SingularityFn2),
  checkFactionInvitations: sf4(C.SingularityFn2),
  joinFaction: sf4(C.SingularityFn2),
  workForFaction: sf4(C.SingularityFn2),
  getFactionWorkTypes: sf4(C.SingularityFn2 / 3),
  getFactionRep: sf4(C.SingularityFn2 / 3),
  getFactionFavor: sf4(C.SingularityFn2 / 3),
  getFactionFavorGain: sf4(C.SingularityFn2 / 4),
  donateToFaction: sf4(C.SingularityFn3),
  createProgram: sf4(C.SingularityFn3),
  getHackingLevelRequirementOfProgram: sf4(C.SingularityFn3),
  commitCrime: sf4(C.SingularityFn3),
  getCrimeChance: sf4(C.SingularityFn3),
  getCrimeStats: sf4(C.SingularityFn3),
  getOwnedAugmentations: sf4(C.SingularityFn3),
  getOwnedSourceFiles: sf4(C.SingularityFn3),
  getAugmentationFactions: sf4(C.SingularityFn3),
  getAugmentationsFromFaction: sf4(C.SingularityFn3),
  getAugmentationPrereq: sf4(C.SingularityFn3),
  getAugmentationPrice: sf4(C.SingularityFn3 / 2),
  getAugmentationBasePrice: sf4(C.SingularityFn3 / 2),
  getAugmentationRepReq: sf4(C.SingularityFn3 / 2),
  getAugmentationStats: sf4(C.SingularityFn3),
  purchaseAugmentation: sf4(C.SingularityFn3),
  softReset: sf4(C.SingularityFn3),
  installAugmentations: sf4(C.SingularityFn3),
  isFocused: sf4(0.1),
  setFocus: sf4(0.1),
  getSaveData: sf4(C.SingularityFn1 / 2),
  exportGame: sf4(C.SingularityFn1 / 2),
  exportGameBonus: sf4(C.SingularityFn1 / 4),
  b1tflum3: sf4(16),
  destroyW0r1dD43m0n: sf4(32),
  getCurrentWork: sf4(0.5),
  getUnlockedAchievements: sf4(C.SingularityFn3),
};

const cloud: CostNode = {
  getServerLimit: 0.05,
  getRamLimit: 0.05,
  getServerCost: 0.25,
  getServerUpgradeCost: 0.1,
  getServerNames: 1.05,
  upgradeServer: 0.25,
  renameServer: 0,
  purchaseServer: 2.25,
  deleteServer: 2.25,
};

const dnet: CostNode = {
  authenticate: 0.4,
  connectToSession: 0.05,
  heartbleed: 0.6,
  openCache: 2,
  probe: C.Scan,
  setStasisLink: 12,
  getStasisLinkLimit: 0,
  getStasisLinkedServers: 0,
  getServer: 2,
  getServerDetails: C.GetServer,
  induceServerMigration: 4,
  unleashStormSeed: 0.1,
  isDarknetServer: C.GetServer,
  memoryReallocation: 1,
  getBlockedRam: 0,
  getDepth: C.GetServer,
  promoteStock: 2,
  phishingAttack: 2,
  getDarknetInstability: 0,
  nextMutation: C.CycleTiming,
  getServerRequiredCharismaLevel: C.GetServer,
  labreport: 0,
  labradar: 0,
};

const gang: CostNode = {
  createGang: C.GangApiBase / 4,
  inGang: 0,
  getMemberNames: C.GangApiBase / 4,
  renameMember: 0,
  getGangInformation: C.GangApiBase / 2,
  getAllGangInformation: C.GangApiBase / 2,
  getMemberInformation: C.GangApiBase / 2,
  canRecruitMember: C.GangApiBase / 4,
  getRecruitsAvailable: C.GangApiBase / 4,
  respectForNextRecruit: C.GangApiBase / 4,
  recruitMember: C.GangApiBase / 2,
  getTaskNames: 0,
  getTaskStats: C.GangApiBase / 4,
  setMemberTask: C.GangApiBase / 2,
  getEquipmentNames: 0,
  getEquipmentCost: C.GangApiBase / 2,
  getEquipmentType: C.GangApiBase / 2,
  getEquipmentStats: C.GangApiBase / 2,
  purchaseEquipment: C.GangApiBase,
  ascendMember: C.GangApiBase,
  getAscensionResult: C.GangApiBase / 2,
  getInstallResult: C.GangApiBase / 2,
  setTerritoryWarfare: C.GangApiBase / 2,
  getChanceToWinClash: C.GangApiBase,
  getBonusTime: 0,
  nextUpdate: C.CycleTiming,
};

const go: CostNode = {
  makeMove: 4,
  passTurn: 0,
  getBoardState: 4,
  getMoveHistory: 0,
  getCurrentPlayer: 0,
  getGameState: 0,
  getOpponent: 0,
  opponentNextTurn: 0,
  resetBoardState: 0,
  analysis: {
    getValidMoves: 8,
    getChains: 16,
    getLiberties: 16,
    getControlledEmptyNodes: 16,
    getStats: 0,
    resetStats: 0,
    setTestingBoardState: 4,
    highlightPoint: 0,
    clearPointHighlight: 0,
    clearAllPointHighlights: 0,
  },
  cheat: {
    getCheatSuccessChance: 1,
    getCheatCount: 1,
    removeRouter: 8,
    playTwoMoves: 8,
    repairOfflineNode: 8,
    destroyNode: 8,
  },
};

const bladeburner: CostNode = {
  inBladeburner: 0,
  getContractNames: 0,
  getOperationNames: 0,
  getBlackOpNames: 0,
  getNextBlackOp: C.BladeburnerApiBase / 2,
  getBlackOpRank: C.BladeburnerApiBase / 2,
  getGeneralActionNames: 0,
  getSkillNames: 0,
  startAction: C.BladeburnerApiBase,
  stopBladeburnerAction: C.BladeburnerApiBase / 2,
  getCurrentAction: C.BladeburnerApiBase / 4,
  getActionTime: C.BladeburnerApiBase,
  getActionCurrentTime: C.BladeburnerApiBase,
  getActionEstimatedSuccessChance: C.BladeburnerApiBase,
  getActionRepGain: C.BladeburnerApiBase,
  getActionRankGain: C.BladeburnerApiBase,
  getActionRankLoss: C.BladeburnerApiBase,
  getActionCountRemaining: C.BladeburnerApiBase,
  getActionMaxLevel: C.BladeburnerApiBase,
  getActionCurrentLevel: C.BladeburnerApiBase,
  getActionAutolevel: C.BladeburnerApiBase,
  getActionSuccesses: C.BladeburnerApiBase,
  setActionAutolevel: C.BladeburnerApiBase,
  setActionLevel: C.BladeburnerApiBase,
  getRank: C.BladeburnerApiBase,
  getSkillPoints: C.BladeburnerApiBase,
  getSkillLevel: C.BladeburnerApiBase,
  getSkillUpgradeCost: C.BladeburnerApiBase,
  upgradeSkill: C.BladeburnerApiBase,
  getTeamSize: C.BladeburnerApiBase,
  setTeamSize: C.BladeburnerApiBase,
  getCityEstimatedPopulation: C.BladeburnerApiBase,
  getCityCommunities: C.BladeburnerApiBase,
  getCityChaos: C.BladeburnerApiBase,
  getCity: C.BladeburnerApiBase,
  switchCity: C.BladeburnerApiBase,
  getStamina: C.BladeburnerApiBase,
  joinBladeburnerFaction: C.BladeburnerApiBase,
  joinBladeburnerDivision: C.BladeburnerApiBase,
  getBonusTime: 0,
  nextUpdate: C.CycleTiming,
};

const corporation: CostNode = {
  hasCorporation: 0,
  canCreateCorporation: 0,
  createCorporation: C.CorporationAction,
  hasUnlock: C.CorporationInfo,
  getUnlockCost: C.CorporationInfo,
  getUpgradeLevel: C.CorporationInfo,
  getUpgradeLevelCost: C.CorporationInfo,
  getInvestmentOffer: C.CorporationInfo,
  getConstants: 0,
  getIndustryData: C.CorporationInfo,
  getMaterialData: C.CorporationInfo,
  acceptInvestmentOffer: C.CorporationAction,
  goPublic: C.CorporationAction,
  bribe: C.CorporationAction,
  getCorporation: C.CorporationInfo,
  getDivision: C.CorporationInfo,
  expandIndustry: C.CorporationAction,
  expandCity: C.CorporationAction,
  purchaseUnlock: C.CorporationAction,
  levelUpgrade: C.CorporationAction,
  issueDividends: C.CorporationAction,
  issueNewShares: C.CorporationAction,
  buyBackShares: C.CorporationAction,
  sellShares: C.CorporationAction,
  getBonusTime: 0,
  nextUpdate: C.CycleTiming,
  sellDivision: C.CorporationAction,
  sellMaterial: C.CorporationAction,
  sellProduct: C.CorporationAction,
  discontinueProduct: C.CorporationAction,
  setSmartSupply: C.CorporationAction,
  setSmartSupplyOption: C.CorporationAction,
  buyMaterial: C.CorporationAction,
  bulkPurchase: C.CorporationAction,
  getWarehouse: C.CorporationInfo,
  getProduct: C.CorporationInfo,
  getMaterial: C.CorporationInfo,
  setMaterialMarketTA1: C.CorporationAction,
  setMaterialMarketTA2: C.CorporationAction,
  setProductMarketTA1: C.CorporationAction,
  setProductMarketTA2: C.CorporationAction,
  exportMaterial: C.CorporationAction,
  cancelExportMaterial: C.CorporationAction,
  purchaseWarehouse: C.CorporationAction,
  upgradeWarehouse: C.CorporationAction,
  makeProduct: C.CorporationAction,
  limitMaterialProduction: C.CorporationAction,
  limitProductProduction: C.CorporationAction,
  getUpgradeWarehouseCost: C.CorporationInfo,
  hasWarehouse: C.CorporationInfo,
  hireEmployee: C.CorporationAction,
  upgradeOfficeSize: C.CorporationAction,
  throwParty: C.CorporationAction,
  buyTea: C.CorporationAction,
  hireAdVert: C.CorporationAction,
  research: C.CorporationAction,
  getOffice: C.CorporationInfo,
  getHireAdVertCost: C.CorporationInfo,
  getHireAdVertCount: C.CorporationInfo,
  getResearchCost: C.CorporationInfo,
  hasResearched: C.CorporationInfo,
  setJobAssignment: C.CorporationAction,
  getOfficeSizeUpgradeCost: C.CorporationInfo,
};

export const RAM_COSTS: CostNode = {
  corporation,
  hacknet,
  stock,
  singularity,
  cloud,
  gang,
  go,
  dnet,
  bladeburner,
  format: { number: 0, ram: 0, percent: 0, time: 0 },
  infiltration: { getPossibleLocations: 0, getInfiltration: C.InfiltrationGetInfiltrations },
  codingcontract: {
    attempt: C.CodingContractBase,
    getContractType: C.CodingContractBase / 2,
    getData: C.CodingContractBase / 2,
    getContract: C.CodingContractBase * (3 / 2),
    getDescription: C.CodingContractBase / 2,
    getNumTriesRemaining: C.CodingContractBase / 5,
    createDummyContract: C.CodingContractBase / 5,
    getContractTypes: 0,
  },
  sleeve: {
    getNumSleeves: C.SleeveBase,
    setToIdle: C.SleeveBase,
    setToShockRecovery: C.SleeveBase,
    setToSynchronize: C.SleeveBase,
    setToCommitCrime: C.SleeveBase,
    setToUniversityCourse: C.SleeveBase,
    travel: C.SleeveBase,
    setToCompanyWork: C.SleeveBase,
    setToFactionWork: C.SleeveBase,
    setToGymWorkout: C.SleeveBase,
    getTask: C.SleeveBase,
    getSleeve: C.SleeveBase,
    getSleeveAugmentations: C.SleeveBase,
    getSleevePurchasableAugs: C.SleeveBase,
    purchaseSleeveAug: C.SleeveBase,
    setToBladeburnerAction: C.SleeveBase,
    getSleeveAugmentationPrice: C.SleeveBase,
    getSleeveAugmentationRepReq: C.SleeveBase,
    purchaseSleeve: C.SleeveBase,
    upgradeMemory: C.SleeveBase,
    getSleeveCost: C.SleeveBase,
    getMemoryUpgradeCost: C.SleeveBase,
  },
  stanek: {
    giftWidth: C.StanekWidth,
    giftHeight: C.StanekHeight,
    chargeFragment: 0.4,
    fragmentDefinitions: C.StanekFragmentDefinitions,
    activeFragments: C.StanekPlacedFragments,
    clearGift: 0,
    canPlaceFragment: 0.5,
    placeFragment: 5,
    getFragment: 2,
    removeFragment: 0.15,
    acceptGift: 2,
  },
  grafting: {
    getAugmentationGraftPrice: 3.75,
    getAugmentationGraftTime: 3.75,
    getGraftableAugmentations: 5,
    graftAugmentation: 7.5,
    waitForOngoingGrafting: 0,
  },

  sprintf: 0,
  vsprintf: 0,
  scan: C.Scan,
  hack: C.Hack,
  hackAnalyzeThreads: 1,
  hackAnalyze: 1,
  hackAnalyzeSecurity: 1,
  hackAnalyzeChance: 1,
  sleep: 0,
  asleep: 0,
  share: 2.4,
  getSharePower: 0.2,
  grow: C.Grow,
  growthAnalyze: 1,
  growthAnalyzeSecurity: 1,
  weaken: C.Weaken,
  weakenAnalyze: 1,
  print: 0,
  printf: 0,
  tprint: 0,
  tprintf: 0,
  clearLog: 0,
  disableLog: 0,
  enableLog: 0,
  isLogEnabled: 0,
  getScriptLogs: 0,
  hasTorRouter: 0.05,
  nuke: C.PortProgram,
  brutessh: C.PortProgram,
  ftpcrack: C.PortProgram,
  relaysmtp: C.PortProgram,
  httpworm: C.PortProgram,
  sqlinject: C.PortProgram,
  run: C.Run,
  exec: C.Exec,
  spawn: C.Spawn,
  self: 0,
  kill: C.Kill,
  killall: C.Kill,
  exit: 0,
  atExit: 0,
  scp: C.Scp,
  ls: C.Scan,
  ps: C.Scan,
  getRecentScripts: C.RecentScripts,
  hasRootAccess: C.HasRootAccess,
  getHostname: C.GetHostname,
  getIP: C.GetHostname,
  getHackingLevel: C.GetHackingLevel,
  getHackingMultipliers: 0.25,
  getHacknetMultipliers: 0.25,
  getBitNodeMultipliers: 4,
  getServer: 2,
  getServerMoneyAvailable: C.GetServer,
  getServerSecurityLevel: C.GetServer,
  getServerBaseSecurityLevel: C.GetServer,
  getServerMinSecurityLevel: C.GetServer,
  getServerRequiredHackingLevel: C.GetServer,
  getServerMaxMoney: C.GetServer,
  getServerGrowth: C.GetServer,
  getServerNumPortsRequired: C.GetServer,
  getServerMaxRam: C.GetServerMaxRam,
  getServerUsedRam: C.GetServerUsedRam,
  dnsLookup: 0.05,
  serverExists: C.GetServer,
  fileExists: C.FileExists,
  isRunning: C.IsRunning,
  write: 0,
  tryWritePort: 0,
  read: 0,
  getFileMetadata: 0,
  peek: 0,
  clear: 0,
  writePort: 0,
  nextPortWrite: 0,
  readPort: 0,
  getPortHandle: 0,
  rm: C.Scp,
  scriptRunning: C.ArbScript,
  scriptKill: C.ArbScript,
  getScriptName: 0,
  getScriptRam: C.GetScript,
  getHackTime: C.GetHackTime,
  getGrowTime: C.GetHackTime,
  getWeakenTime: C.GetHackTime,
  getTotalScriptIncome: C.GetScript,
  getScriptIncome: C.GetScript,
  getTotalScriptExpGain: C.GetScript,
  getScriptExpGain: C.GetScript,
  getRunningScript: C.GetRunningScript,
  ramOverride: 0,
  prompt: 0,
  wget: 0,
  getFavorToDonate: C.GetFavorToDonate,
  getPlayer: C.SingularityFn1 / 4,
  getMoneySources: C.GetMoneySourcesCost,
  mv: 0,
  getResetInfo: 1,
  getFunctionRamCost: 0,
  toast: 0,
  clearPort: 0,
  alert: 0,
  flags: 0,
};

/** SF4Cost: 16x with no SF4, 4x at level 2, 1x at level 3+ or inside BN4.
 * (bitburner-src/src/Netscript/RamCostGenerator.ts SF4Cost @ v3.0.1.) */
function sf4Multiplier(ctx: RamCostContext): number {
  if (ctx.bitNode === 4) return 1;
  const level = ctx.sf4Level ?? 0;
  if (level <= 1) return 16;
  if (level === 2) return 4;
  return 1;
}

/** Cost of an internal `ns.<path>`, dotted. The game's internal getRamCost
 * defaults an unknown path to 0 when its strict flag is absent. Public
 * `ns.getFunctionRamCost`, however, passes that strict flag and throws. */
function isSf4(node: CostNode): node is Sf4Cost {
  return typeof node === "object" && typeof (node as Sf4Cost).sf4 === "number";
}

export function getRamCost(path: string, ctx: RamCostContext = {}): number {
  let node: CostNode | undefined = RAM_COSTS;
  for (const branch of path.split(".")) {
    if (node === undefined || typeof node !== "object" || isSf4(node)) return 0;
    node = node[branch];
  }
  if (node === undefined) return 0;
  if (typeof node === "number") return node;
  if (isSf4(node)) return node.sf4 * sf4Multiplier(ctx);
  return 0;
}

/** Public `ns.getFunctionRamCost` semantics. `baseCost` is a documented
 * special name; an unknown or namespace-only path is an API error, never free
 * RAM (NetscriptFunctions.ts:1501, RamCostGenerator.ts:743 @ v3.0.1). */
export function getFunctionRamCost(path: string, ctx: RamCostContext = {}): number {
  if (path === "baseCost") return SCRIPT_BASE_RAM_GB;
  let node: CostNode = RAM_COSTS;
  for (const branch of path.split(".")) {
    const next: CostNode | undefined = typeof node === "object" && !isSf4(node) ? node[branch] : undefined;
    if (next === undefined) {
      // Upstream deliberately throws a string for a missing leaf.
      throw `No ram cost is defined for (ns.${path})`;
    }
    if (typeof next === "object" && !isSf4(next)) {
      node = next;
      continue;
    }
    return typeof next === "number" ? next : next.sf4 * sf4Multiplier(ctx);
  }
  throw new Error(`Tried to get ram cost for ns.${path} but the value was an invalid type`);
}
