/** Regenerates shared/strategy/target-bands.ts from the transcribed server
 * ranges. Run `bun run tools/gen-target-bands.ts` after a vendor bump changes
 * shared/features/servers.ts; sim/tests/target-bands.test.ts fails until the
 * committed table matches a fresh computation. */
import { computeTargetBands } from "../shared/strategy/bounds.ts";

const OUT = new URL("../shared/strategy/target-bands.ts", import.meta.url);

const bands = computeTargetBands();
const rows = bands
  .map((b) => `  { from: ${b.from}, to: ${b.to}, contenders: [${b.contenders.map((c) => JSON.stringify(c)).join(", ")}] },`)
  .join("\n");

const source = `// Generated by tools/gen-target-bands.ts — DO NOT EDIT (data only; the
// lookup helper is contendersAt in bounds.ts, kept out of this file so logic
// can never be silently reverted by a regeneration).
// Pinned by sim/tests/target-bands.test.ts; regenerate after a vendor bump.
import type { TargetBand } from "./bounds.ts";

/** Which servers can contest the RAM-unbound steady-state farm optimum, per
 * hacking-skill band, over EVERY possible world-generation roll. Contract and
 * proof obligations: see computeTargetBands in bounds.ts. Never used to gate
 * the runtime evaluator — that prunes exactly, from live rolls. */
export const TARGET_BANDS: readonly TargetBand[] = [
${rows}
];
`;

await Bun.write(OUT, source);
console.log(`wrote ${bands.length} bands to shared/strategy/target-bands.ts`);
