/** Bundle the standalone combined playbook+neural Bitburner script.
 *
 * One self-contained ES module: the neural-stripped merged playbook, the
 * deployed small5 artifact, the production decision engine and WebGPU
 * backend, and the combined driver — isolated from the worker, RAM planning,
 * and every other game feature. This is the shareable proof build; the
 * production integration lives in `game/`.
 *
 * Usage: bun run go:combined:standalone [--out PATH] [--minify]
 */
import { existsSync } from "node:fs";
import { join } from "node:path";
import * as esbuild from "esbuild";
import { inlinePlaybookScript } from "./go-playbook-inline.ts";

const ROOT = join(import.meta.dir, "..");
const PLAYBOOK = join(ROOT, "go-ai", "derivatives", "playbook-combined", "merged", "playbook.phase.js");

function stringFlag(name: string, fallback: string): string {
  const index = Bun.argv.indexOf(name);
  if (index < 0) return fallback;
  const value = Bun.argv[index + 1];
  if (!value) throw new Error(`${name} requires a value`);
  return value;
}

if (!existsSync(PLAYBOOK)) {
  throw new Error(`stripped merged playbook missing at ${PLAYBOOK}; run go:playbook:pack first`);
}
const outfile = stringFlag("--out", join(ROOT, "go-ai", "derivatives", "combined-standalone.js"));

// The generated playbook module is too large for esbuild's parser, so the
// driver is bundled alone and the playbook rides along as an inlined classic
// script that assigns `globalThis.__combinedPlaybook` before the driver runs.
const driver = await esbuild.build({
  entryPoints: [join(import.meta.dir, "combined-standalone", "main.ts")],
  bundle: true,
  format: "esm",
  target: "es2022",
  write: false,
  minify: Bun.argv.includes("--minify"),
  logLevel: "warning",
});
esbuild.stop();
const playbookScript = inlinePlaybookScript(await Bun.file(PLAYBOOK).text());
await Bun.write(outfile,
  `// Generated by tools/go-build-combined-standalone.ts. Do not edit.\n`
  + `// Combined IPvGO driver: neural-stripped phase playbook first, deployed\n`
  + `// small5 WebGPU model as the fallback. Isolated proof build.\n`
  + `${playbookScript}\n${driver.outputFiles[0]!.text}`);
const bytes = (await Bun.file(outfile).arrayBuffer()).byteLength;
console.log(`wrote ${outfile}: ${(bytes / 1024 / 1024).toFixed(2)} MB`
  + ` (driver ${(driver.outputFiles[0]!.text.length / 1024).toFixed(0)} KB`
  + ` + playbook ${(playbookScript.length / 1024 / 1024).toFixed(2)} MB)`);
