/** Export go-ai v7 checkpoints into the compact runtime artifacts the game
 * imports. Checkpoints stay full-precision text in go-ai/; this tool reorders
 * the tensors for inference, narrows them to float32, and emits generated TS
 * modules under shared/strategy/go/neural/models/.
 *
 * Usage: bun run go:export
 *    or: bun run tools/go-export-model.ts <checkpoint.model> <profileName>
 */
import { goValueWeightSizes } from "../shared/strategy/go/neural/artifact.ts";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const MODELS_DIR = join(ROOT, "shared", "strategy", "go", "neural", "models");

interface Checkpoint {
  extent: number;
  hidden: number;
  opponentFeatures: number;
  w1: number[];
  b1: number[];
  w2: number[];
  b2: number[];
  conv: number[];
  convBias: number[];
}

function parseCheckpoint(text: string, source: string): Checkpoint {
  const tokens = text.split(/\s+/).filter((token) => token.length > 0);
  let cursor = 0;
  const next = () => {
    const token = tokens[cursor++];
    if (token === undefined) throw new Error(`${source}: truncated checkpoint`);
    return token;
  };
  const nextNumber = () => {
    const value = Number(next());
    if (!Number.isFinite(value)) throw new Error(`${source}: non-finite value at token ${cursor - 1}`);
    return value;
  };
  const magic = next();
  if (magic !== "bitburner-go-value-v7") {
    throw new Error(`${source}: expected a v7 checkpoint, found ${magic}`);
  }
  const extent = nextNumber();
  const hidden = nextNumber();
  const opponentFeatures = nextNumber();
  const vector = (expected: number, name: string) => {
    const count = nextNumber();
    if (count !== expected) throw new Error(`${source}: ${name} holds ${count} values; expected ${expected}`);
    return Array.from({ length: count }, nextNumber);
  };
  const sizes = goValueWeightSizes(hidden, opponentFeatures);
  const checkpoint: Checkpoint = {
    extent,
    hidden,
    opponentFeatures,
    w1: vector(sizes.w1, "w1"),
    b1: vector(sizes.b1, "b1"),
    w2: vector(sizes.w2, "w2"),
    b2: vector(sizes.b2, "b2"),
    conv: vector(sizes.conv, "conv"),
    convBias: vector(sizes.convBias, "convBias"),
  };
  if (cursor !== tokens.length) throw new Error(`${source}: ${tokens.length - cursor} trailing tokens`);
  return checkpoint;
}

function encodeArtifactWeights(checkpoint: Checkpoint): string {
  const values = new Float32Array([
    ...checkpoint.conv,
    ...checkpoint.convBias,
    ...checkpoint.w1,
    ...checkpoint.b1,
    ...checkpoint.w2,
    ...checkpoint.b2,
  ]);
  return Buffer.from(values.buffer).toString("base64");
}

async function exportModel(checkpointPath: string, profile: string): Promise<void> {
  const text = await Bun.file(checkpointPath).text();
  const source = relative(ROOT, checkpointPath);
  const checkpoint = parseCheckpoint(text, source);
  const constant = `${profile.toUpperCase()}_GO_MODEL`;
  const module = `/** Generated by tools/go-export-model.ts from ${source}. Do not edit. */
import type { GoValueModelArtifact } from "../artifact.ts";

export const ${constant}: GoValueModelArtifact = {
  format: "bitburner-go-value-v7",
  extent: ${checkpoint.extent},
  hidden: ${checkpoint.hidden},
  opponentFeatures: ${checkpoint.opponentFeatures},
  source: ${JSON.stringify(source)},
  weights:
    "${encodeArtifactWeights(checkpoint)}",
};
`;
  const target = join(MODELS_DIR, `${profile}.ts`);
  await Bun.write(target, module);
  console.log(`${source} -> ${relative(ROOT, target)} (extent ${checkpoint.extent}, hidden ${checkpoint.hidden}, heads ${Math.max(checkpoint.opponentFeatures, 1)})`);
}

const DEFAULT_EXPORTS: readonly [string, string][] = [
  [join(ROOT, "go-ai", "small5-champion.model"), "small5"],
  [join(ROOT, "go-ai", "daemon19-champion.model"), "daemon19"],
];

if (Bun.argv.length > 2) {
  const [checkpointPath, profile] = [Bun.argv[2]!, Bun.argv[3]];
  if (!profile || !/^[a-z][a-z0-9]*$/.test(profile)) {
    throw new Error("usage: bun run tools/go-export-model.ts <checkpoint.model> <profile-name>");
  }
  await exportModel(checkpointPath, profile);
} else {
  for (const [checkpointPath, profile] of DEFAULT_EXPORTS) await exportModel(checkpointPath, profile);
}
