import type { PasswordEvidence } from "./evidence.ts";

/** Darknet data files generated by the pinned game checkout.
 *
 * Keep these references beside the parser: when upstream changes a filename,
 * clue grammar, or probability, these are the three sources to diff first.
 *
 * Source: ../bitburner-src
 *   src/DarkNet/effects/effects.ts (`addClue`, including branch probabilities)
 *   src/DarkNet/models/dictionaryData.ts (filename and content pools)
 *   src/DarkNet/models/hintNotes.ts (`.lit` mechanic hints)
 */
const GENERATED_FILES = new Set<string>([
  "secrets.data.txt",
  "password.data.txt",
  "key.data.txt",
  "credentials.data.txt",
  "login.data.txt",
  "admin.data.txt",
  "root.data.txt",
  "access.data.txt",
  "thoughts.data.txt",
  "notes.data.txt",
  "journal.data.txt",
  "search_history.data.txt",
  "dreams.data.txt",
  "THE_TRUTH.data.txt",
]);

type DarknetFileClue =
  | { kind: "named-password"; hostname: string; password: string }
  | { kind: "neighbour-password"; password: string }
  | { kind: "evidence"; hostname: string; evidence: PasswordEvidence };

export function isDarknetDataFile(filename: string): boolean {
  return GENERATED_FILES.has(filename);
}

/** An unnamed first-auth clue can be bound to neighbours only while all three
 * observations describe the same network generation. */
export function exactNeighbourClueEpoch(
  authenticationEpoch: number | undefined,
  probeEpoch: number | undefined,
  inventoryEpoch: number,
): boolean {
  return authenticationEpoch !== undefined
    && probeEpoch === authenticationEpoch
    && inventoryEpoch === authenticationEpoch;
}

/** Parse without RegExp: this module reaches a game bundle, where a RegExp
 * `exec` reference can be mistaken for the billable Netscript `exec` member. */
export function parseDarknetFileClue(content: string, at: number): DarknetFileClue | undefined {
  const namedPrefix = "Server: ";
  const passwordMarker = " Password: \"";
  if (content.startsWith(namedPrefix) && content.endsWith("\"")) {
    const marker = content.indexOf(passwordMarker, namedPrefix.length);
    if (marker > namedPrefix.length) {
      const hostname = content.slice(namedPrefix.length, marker);
      const password = content.slice(marker + passwordMarker.length, -1);
      if (hostname.length > 0 && password.length > 0) return { kind: "named-password", hostname, password };
    }
  }

  const rememberedPrefix = "Remember this password: ";
  if (content.startsWith(rememberedPrefix)) {
    const password = content.slice(rememberedPrefix.length);
    if (password.length > 0) return { kind: "neighbour-password", password };
  }

  const containsPrefix = "The password for ";
  const containsMarker = " contains ";
  if (content.startsWith(containsPrefix)) {
    const marker = content.indexOf(containsMarker, containsPrefix.length);
    if (marker > containsPrefix.length) {
      const hostname = content.slice(containsPrefix.length, marker);
      const pair = content.slice(marker + containsMarker.length);
      const and = pair.indexOf(" and ");
      if (hostname.length > 0 && and > 0) {
        const first = pair.slice(0, and);
        const second = pair.slice(and + 5);
        if (first.length === 1 && second.length === 1) {
          return { kind: "evidence", hostname, evidence: { kind: "contains", chars: [first, second], at } };
        }
      }
    }
  }

  return undefined;
}
