/** Compact runtime artifact for the go-ai v7 board-value network.
 *
 * The trainer's `.model` checkpoints stay in go-ai/ as full-precision text.
 * The game consumes this derived form: one JSON-shaped module with a single
 * base64 float32 blob, generated by `bun run go:export`. Weights are ordered
 * for the forward pass (convolution first), unlike the checkpoint file.
 */

export interface GoValueModelArtifact {
  format: "bitburner-go-value-v7";
  /** Feature extent. Boards smaller than the extent are padded as offline. */
  extent: number;
  /** Hidden tanh units in the dense value layer. */
  hidden: number;
  /** Opponent one-hot inputs and output heads; 0 means one shared head. */
  opponentFeatures: number;
  /** Little-endian float32: conv, convBias, w1, b1, w2, b2. */
  weights: string;
  /** Provenance recorded by the exporter; not used at runtime. */
  source: string;
}

export const GO_SPATIAL_CHANNELS = 8;
export const GO_SPATIAL_POOL_EXTENT = 5;
export const GO_VALUE_OUTPUTS = 3;

export interface GoValueWeights {
  extent: number;
  hidden: number;
  opponentFeatures: number;
  headCount: number;
  /** Pooled spatial inputs plus the opponent one-hot. */
  denseInputSize: number;
  /** [channel][plane][dx+1][dy+1] exactly as the trainer indexes it. */
  conv: Float32Array;
  convBias: Float32Array;
  /** [hidden][denseInput] row-major. */
  w1: Float32Array;
  b1: Float32Array;
  /** [head*3+output][hidden] row-major. */
  w2: Float32Array;
  b2: Float32Array;
}

/** Tensor shapes for a v7 profile. The spatial trunk always pools to a fixed
 * 5x5 grid, so sizes depend on width and head count but never on the board
 * extent. */
export function goValueWeightSizes(hidden: number, opponentFeatures: number): {
  conv: number;
  convBias: number;
  w1: number;
  b1: number;
  w2: number;
  b2: number;
  denseInputSize: number;
  headCount: number;
} {
  const denseInputSize = GO_SPATIAL_CHANNELS * GO_SPATIAL_POOL_EXTENT * GO_SPATIAL_POOL_EXTENT
    + opponentFeatures;
  const headCount = Math.max(opponentFeatures, 1);
  return {
    conv: GO_SPATIAL_CHANNELS * 3 * 3 * 3,
    convBias: GO_SPATIAL_CHANNELS,
    w1: hidden * denseInputSize,
    b1: hidden,
    w2: headCount * GO_VALUE_OUTPUTS * hidden,
    b2: headCount * GO_VALUE_OUTPUTS,
    denseInputSize,
    headCount,
  };
}

/** Decode the artifact into typed weight views. The base64 source string is
 * not retained; callers should let the artifact module itself be the only
 * long-lived copy. */
export function loadGoValueWeights(artifact: GoValueModelArtifact): GoValueWeights {
  if (artifact.format !== "bitburner-go-value-v7") {
    throw new Error(`unsupported go value artifact format ${artifact.format}`);
  }
  const sizes = goValueWeightSizes(artifact.hidden, artifact.opponentFeatures);
  const total = sizes.conv + sizes.convBias + sizes.w1 + sizes.b1 + sizes.w2 + sizes.b2;
  const binary = atob(artifact.weights);
  if (binary.length !== total * 4) {
    throw new Error(`go value artifact holds ${binary.length} bytes; expected ${total * 4}`);
  }
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index++) bytes[index] = binary.charCodeAt(index);
  const values = new Float32Array(bytes.buffer);
  for (const value of values) {
    if (!Number.isFinite(value)) throw new Error("go value artifact contains a non-finite weight");
  }
  let offset = 0;
  const take = (count: number) => {
    const view = values.subarray(offset, offset + count);
    offset += count;
    return view;
  };
  return {
    extent: artifact.extent,
    hidden: artifact.hidden,
    opponentFeatures: artifact.opponentFeatures,
    headCount: sizes.headCount,
    denseInputSize: sizes.denseInputSize,
    conv: take(sizes.conv),
    convBias: take(sizes.convBias),
    w1: take(sizes.w1),
    b1: take(sizes.b1),
    w2: take(sizes.w2),
    b2: take(sizes.b2),
  };
}
